add create and ifexists to line type

diff --git a/cdist/conf/type/__line/gencode-remote b/cdist/conf/type/__line/gencode-remote
--- a/cdist/conf/type/__line/gencode-remote
+++ b/cdist/conf/type/__line/gencode-remote
@@ -34,8 +34,16 @@ state_should="$(cat "$__object/parameter/state")"
 state_is="$(cat "$__object/explorer/state")"
 
 if [ -z "$state_is" ]; then
-   printf 'The file "%s" is missing. Please create it before using %s on it.\n' "$file" "${__type##*/}" >&2
-   exit 1
+   if [ -f "$__object/parameter/create" ]; then
+      echo "touch $file"
+   else
+      # only bark if the file should exists
+      if [ -f "$__object/parameter/ifexists" ]; then
+          exit 0
+      fi
+      printf 'The file "%s" is missing. Please create it before using %s on it.\n' "$file" "${__type##*/}" >&2
+      exit 1
+   fi
 fi
 
 if [ "$state_should" = "$state_is" ] || \
