MJS: Convert to TTNv3

diff --git a/cdist/conf/manifest/init b/cdist/conf/manifest/init
--- a/cdist/conf/manifest/init
+++ b/cdist/conf/manifest/init
@@ -164,16 +164,37 @@ __config_file /opt/ttn-gateway/global_conf.json \
   --onchange 'systemctl restart packet-forwarder.service' \
   --source $__files/forwarder/global_conf.json
 
-# Get the access key to use from TTN
-ttnkey=$(ttnctl gateways info "${hostname}" | grep 'Access Key' | sed 's/\s*Access Key: //')
 
-if [ -z "$ttnkey" ]; then
-  # If we couldn't get the key, assume that one is already configured.
-  # TODO: Check that there is a pre-existing config file and error out
-  # otherwise?
-  echo "Could not figure out TTN gateway key, skipping gateway configuration!" 2>1
+# Check existing conf
+get_forwarder_conf() {
+  # Strip comments from JSON file, since jq expects fully valid JSON
+  grep -v "^\s*//" "$__explorer/packet_forwarder_local_config" | \
+    jq --raw-output ".gateway_conf.servers|.[0].$1"
+}
+
+tgt_addr=eu1.cloud.thethings.network:1881
+cur_addr=$(get_forwarder_conf server_address)
+cur_id=$(get_forwarder_conf serv_gw_id)
+cur_key=$(get_forwarder_conf serv_gw_key)
+
+# If the address changes (e.g. ttnv2 -> ttnv3), the id changes, or there
+# is no key yet, generate a new key
+if [ "$cur_addr" != "$tgt_addr" -o "$cur_id" != "$hostname" -o -z "$cur_key" ]; then
+  today="$(date +%Y-%m-%d)"
+  key_json=$(ttn-lw-cli gateways api-keys create "$hostname" --name "Gateway key by cdist ($today)" --right-gateway-link)
+  cur_key=$(echo "$key_json" | jq --raw-output '.key')
+  if [ -z "$cur_key" ]; then
+    echo "Failed to add API key" >&2
+    exit 1
+  fi
+  echo "Generated TTN gateway key: ${cur_key}" >&2
 else
-  echo "Found TTN gateway key: ${ttnkey}"
+  echo "Using existing TTN gateway key: ${cur_key}" >&2
+fi
+
+# If we have a key (existing or just generated) update the config file
+# (possibly identical to the current file).
+if [ -n "$cur_key" ]; then
   # TODO: Start and configure gateway using something like:
   #   https://github.com/jpmeijers/ttn-resin-gateway-rpi/blob/master/run.py
   # Possibly using Adafruit_BBIO for GPIO instead of ResetIC880A above:
@@ -187,9 +208,9 @@ else
         "servers": [
             {
                 "serv_type": "ttn",
-                "server_address": "router.eu.thethings.network",
+                "server_address": "${tgt_addr}",
                 "serv_gw_id": "${hostname}",
-                "serv_gw_key": "${ttnkey}",
+                "serv_gw_key": "${cur_key}",
                 "serv_enabled": true
             }
         ],
